deps_list = [ 'Bilgisayar Mühendisliği',
              'Biyomedikal Mühendisliği',
              'Çevre Mühendisliği',
              'Elektrik-Elektronik Mühendisliği',
              'Gıda Mühendisliği',
              'Geomatik Mühendisliği',
              'İnşaat Mühendisliği',
              'Maden Mühendisliği',
              'Makine Mühendisliği',
              'Metalurji ve Malzeme Mühendisliği',
              'Büro Yönetimi ve Yönetici Asistanlığı',
              'Çağrı Merkezi Hizmetleri',
              'Gıda Kalite Kontrolü ve Analizi',
              'Gıda Teknolojisi',
              'İnsan Kaynakları Yönetimi',
              'İşletme Yönetimi',
              'Mobilya ve Dekorasyon',
              'Muhasebe ve Vergi Uygulamaları',
              'Ormancılık ve Orman Ürünleri',
              'Turizm ve Otel İşletmeciliği',
              'Uygulamalı İngilizce ve Çevirmenlik (İngilizce )',
              'Bankacılık ve Sigortacılık',
              'Elektrik',
              'Elektronik Haberleşme Teknolojisi',
              'Elektronik Teknolojisi',
              'Gemi İnşaatı',
              'Gemi Makineleri İşletme',
              'İnşaat Teknolojisi',
              'İşletme Yönetimi',
              'Kontrol ve Otomasyon Teknolojisi',
              'Makine',
              'Metalurji',
              'Muhasebe ve Vergi Uygulamaları',
              'Yapı Denetimi',
              'Yapı Ressamlığı',
              'Halkla İlişkiler ve Tanıtım',
              'Mimari Dekoratif Sanatlar',
              'Tıbbi ve Aromatik Bitkiler',
              'Arkeoloji',
              'Biyoloji',
              'İngiliz Dili ve Edebiyatı',
              'Kimya',
              'Matematik',
              'Moleküler Biyoloji ve Genetik',
              'Psikoloji',
              'Sosyoloji',
              'Tarih',
              'Türk Dili ve Edebiyatı',
              'Opera',
              'Oyunculuk',
              'Yaylı Çalgılar',
              'Yaylı Çalgılar Yapımı',
              'Tıp',
              'Tıp Fakültesi',
              'Ağız ve Diş Sağlığı',
              'Ameliyathane Hizmetleri',
              'Anestezi',
              'Çocuk Gelişimi',
              'Eczane Hizmetleri',
              'İlk ve Acil Yardım',
              'Odyometri',
              'Optisyenlik',
              'Patoloji Laboratuvar Teknikleri',
              'Saç Bakımı ve Güzellik Hizmetleri',
              'Tıbbi Dokümantasyon ve Sekreterlik',
              'Tıbbi Görüntüleme Teknikleri',
              'Tıbbi Laboratuvar Teknikleri',
              'Tıbbi Tanıtım ve Pazarlama',
              'Yaşlı Bakımı',
              'Yaşlı Bakımı (KKTC Uyruklu)',
              'Aşçılık',
              'Bilgisayar Programcılığı',
              'Büro Yönetimi ve Yönetici Asistanlığı',
              'Geleneksel El Sanatları',
              'İşletme Yönetimi',
              'Kimya Teknolojisi',
              'Menkul Kıymetler ve Sermaye Piyasası',
              'Muhasebe ve Vergi Uygulamaları',
              'Özel Güvenlik ve Koruma',
              'Turizm ve Otel İşletmeciliği',
              'Uygulamalı İngilizce ve Çevirmenlik (İngilizce )',
              'Yerel Yönetimler',
              'Fizyoterapi ve Rehabilitasyon',
              'Hemşirelik',
              'Eczacılık Fakültesi',
              'Fen Bilgisi Öğretmenliği',
              'İlköğretim Matematik Öğretmenliği',
              'Okul Öncesi Öğretmenliği',
              'Özel Eğitim Öğretmenliği',
              'Rehberlik ve Psikolojik Danışmanlık',
              'Sınıf Öğretmenliği',
              'Sosyal Bilgiler Öğretmenliği',
              'Türkçe Öğretmenliği',
              'Zihin Engelliler Öğretmenliği',
              'Çalışma Ekonomisi ve Endüstri İlişkileri',
              'İktisat',
              'İşletme',
              'Maliye',
              'Siyaset Bilimi ve Kamu Yönetimi',
              'Siyaset Bilimi ve Kamu Yönetimi (KKTC Uyruklu)',
              'Uluslararası Ticaret ve İşletmecilik',
              'Diş Hekimliği',
              'Bilgi Güvenliği Teknolojisi',
              'Deniz ve Liman İşletmeciliği',
              'Grafik Tasarımı',
              'Resim',
              'İlahiyat',
              'Biyomedikal Cihaz Teknolojisi',
              'Harita ve Kadastro',
              'İnşaat Teknolojisi',
              'İşletme Yönetimi',
              'Lojistik',
              'Maden Teknolojisi',
              'Muhasebe ve Vergi Uygulamaları',
              'Radyo ve Televizyon Programcılığı',
              'Turizm ve Otel İşletmeciliği',
              'Turizm ve Otel İşletmeciliği (KKTC Uyruklu)',
              'Denizcilik İşletmeleri Yönetimi',
              'Beden Eğitimi ve Spor Öğretmenliği',
              'Podoloji']